import type { ITopUpsAndExpenses } from "./types";

export const topUpsAndExpensesList: ITopUpsAndExpenses[] = [
  {
    id: 1,
    type: "Top-Ups",
    date: "",
    amount: "",
    counter_party: "",
    expenses_type: "",
    expenses_date: "",
    expenses_counter_party: "",
    expenses_amount: "",
    start_month: "",
    end_month: "",
    quick_month_list: "",
    opening_balance: "",
    closing_balance: "",
    linked_card_number: "",
    linked_card_holder_name: "",
    month_and_year: "",
    cvv: "",
  },
  {
    id: 2,
    type: "Expenses",
    date: "",
    amount: "",
    counter_party: "",
    expenses_type: "",
    expenses_date: "",
    expenses_counter_party: "",
    expenses_amount: "",
    start_month: "",
    end_month: "",
    quick_month_list: "",
    opening_balance: "",
    closing_balance: "",
    linked_card_number: "",
    linked_card_holder_name: "",
    month_and_year: "",
    cvv: "",
  },
  {
    id: 3,
    type: "Top-Ups & Expenses",
    date: "",
    amount: "",
    counter_party: "",
    expenses_type: "",
    expenses_date: "",
    expenses_counter_party: "",
    expenses_amount: "",
    start_month: "",
    end_month: "",
    quick_month_list: "",
    opening_balance: "",
    closing_balance: "",
    linked_card_number: "",
    linked_card_holder_name: "",
    month_and_year: "",
    cvv: "",
  },
];